export const Colors = {
  light: {
    background: '#F5F7FA',
    surface: '#FFFFFF',
    surfaceSecondary: '#F0F2F5',
    surfaceTertiary: '#E8ECF0',
    primary: '#1A1A2E',
    primaryLight: '#4A4A6A',
    accent: '#6366F1',
    accentLight: '#818CF8',
    accentGradient: ['#6366F1', '#8B5CF6'] as const,
    success: '#10B981',
    successLight: '#34D399',
    warning: '#F59E0B',
    warningLight: '#FBBF24',
    error: '#EF4444',
    errorLight: '#F87171',
    text: '#1A1A2E',
    textOnAccent: '#FFFFFF',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    shadow: 'rgba(26, 26, 46, 0.08)',
    shadowStrong: 'rgba(26, 26, 46, 0.15)',
    card: '#FFFFFF',
    cardElevated: '#FFFFFF',
    overlay: 'rgba(0, 0, 0, 0.5)',
    mapTile: 'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',
    mapTileDark: 'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',
  },
  dark: {
    background: '#0F0F1A',
    surface: '#1A1A2E',
    surfaceSecondary: '#252542',
    surfaceTertiary: '#303055',
    primary: '#F8FAFC',
    primaryLight: '#E2E8F0',
    accent: '#818CF8',
    accentLight: '#A5B4FC',
    accentGradient: ['#818CF8', '#A78BFA'] as const,
    success: '#34D399',
    successLight: '#6EE7B7',
    warning: '#FBBF24',
    warningLight: '#FCD34D',
    error: '#F87171',
    errorLight: '#FCA5A5',
    text: '#F8FAFC',
    textOnAccent: '#0F0F1A',
    textSecondary: '#94A3B8',
    textMuted: '#64748B',
    border: '#334155',
    borderLight: '#1E293B',
    shadow: 'rgba(0, 0, 0, 0.4)',
    shadowStrong: 'rgba(0, 0, 0, 0.6)',
    card: '#1A1A2E',
    cardElevated: '#252542',
    overlay: 'rgba(0, 0, 0, 0.7)',
    mapTile: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
    mapTileDark: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
  },
};

export type ColorTheme = (typeof Colors)[keyof typeof Colors];
